// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
    public static final class DriveConstants {
        // motor ids
        public static final int LEFT_FRONT_MOTOR_ID = 8;
        public static final int RIGHT_FRONT_MOTOR_ID = 2;
        public static final int LEFT_MIDDLE_MOTOR_ID = 7;
        public static final int RIGHT_MIDDLE_MOTOR_ID = 3;
        public static final int BACK_LEFT_MOTOR_ID = 6;
        public static final int BACK_RIGHT_MOTOR_ID = 4;
    }

    public static final class JoystickConstants {
        // joystick ports
    public static final int JOYSTICK_PORT = 1;
    public static final int GO_TO_90 = 3;
    public static final int GO_TO_180 = 4;
    public static final int GO_TO_NEG90 =7;
    public static final int GO_TO_0 = 8;
    public static final int RESET = 9;
    }
}

